import { app, clipboard, globalShortcut, ipcMain, Menu, nativeImage, Tray } from 'electron';
import { join } from 'node:path';
import { cleanupCaptureDir, initCaptureDir } from './capture.js';
import { initClicks } from './clicks.js';
import { answerStep, bindStepKeys, cancelStep, currentStep, keyLabel } from './steps.js';
import {
    createHud,
    hasLocalVoice,
    hudWindow,
    onVoicesKnown,
    pushMessage,
    setHudContentProtection,
    setStatus,
    stopSpeaking,
    toggleHud
} from './hud.js';
import { startIdleWatch, stopIdleWatch } from './idle.js';
import { disposeImageWorker } from './imageWorker.js';
import {
    startMcpServer,
    displacedPort,
    mcpActiveRequests,
    mcpAuthedUrl,
    mcpUrl,
    type McpServerHandle
} from './mcp/server.js';
import {
    destroyOverlay,
    initOverlay,
    isContentProtected,
    pushState,
    setContentProtection
} from './overlay.js';
import { store } from './store.js';
import { startAnchorTracking, stopAnchorTracking } from './anchors.js';
import { stopUia } from './uia.js';
import { currentProviderLabel, initAgentHost, isBusy } from './agent/host.js';
import { applyOpenAtLogin, settings, startedHidden, updateSettings } from './settings.js';

const DEFAULT_PORT = Number(process.env.SCREEN_OVERLAY_PORT || 7777);

let tray: Tray | null = null;
let mcp: McpServerHandle | null = null;

// A second instance would fight the first for global shortcuts and bind the
// same port, so hand focus back to the running one instead.
if (!app.requestSingleInstanceLock()) {
    app.quit();
} else {
    app.on('second-instance', () => hudWindow()?.show());
    void main();
}

async function main(): Promise<void> {
    // X11 composites transparent windows only with this switch. Windows and
    // macOS handle transparency natively and the switch is a no-op there.
    if (process.platform === 'linux') {
        app.commandLine.appendSwitch('enable-transparent-visuals');
    }

    await app.whenReady();

    const prefs = settings();
    setContentProtection(!prefs.showInCapture);
    applyOpenAtLogin(prefs.openAtLogin);

    initCaptureDir();
    initOverlay();
    initClicks();
    initAgentHost();
    createHud(isContentProtected());
    if (startedHidden()) hudWindow()?.hide();
    registerIpc();
    registerShortcuts();

    try {
        mcp = await startMcpServer(DEFAULT_PORT);
        const moved = displacedPort();
        pushMessage(
            'system',
            `Overlay ready on ${mcp.url}. Access requires a token — use "Copy MCP URL" in the tray ` +
                'menu, or run scripts/connect.mjs, to get the full URL.' +
                (moved
                    ? ` NOTE: port ${moved} was already in use, so this moved to ${mcp.port}. ` +
                      'Any agent configured with the old port needs updating.'
                    : '')
        );
    } catch (err) {
        pushMessage('error', `Could not start the MCP server on port ${DEFAULT_PORT}: ${(err as Error).message}`);
    }

    // Keeps anchored annotations glued to the windows and controls they point at.
    startAnchorTracking();

    // Fades what an agent that went quiet left on screen.
    startIdleWatch(mcpActiveRequests);

    buildTray();
    publishStatus();
    setInterval(publishStatus, 2000).unref?.();

    // This is a tray app; closing the panel should not exit.
    app.on('window-all-closed', () => {
        /* keep running */
    });
}

function publishStatus(): void {
    setStatus({
        mcpUrl: mcpUrl(),
        mcpConnected: mcpActiveRequests(),
        contentProtection: isContentProtected(),
        provider: currentProviderLabel(),
        busy: isBusy()
    });
}

function registerIpc(): void {
    ipcMain.handle('app:clear-annotations', () => {
        store.clear();
    });
    ipcMain.handle('app:copy-mcp-url', () => {
        // The authed form, otherwise pasting it anywhere yields 401.
        clipboard.writeText(mcpAuthedUrl());
        pushMessage('system', 'MCP URL copied to the clipboard.');
    });
    ipcMain.on('app:hide-hud', () => hudWindow()?.hide());
}

function registerShortcuts(): void {
    // Toggle the chat panel.
    globalShortcut.register('Control+Shift+O', () => toggleHud(true));
    // Panic button: wipe everything drawn on screen and end the pending step.
    globalShortcut.register('Control+Shift+X', () => {
        cancelStep('clear');
        store.clear();
    });

    // Done, Stuck and (in click mode) Escape, held only while a step is
    // pending; see bindStepKeys for why.
    bindStepKeys(globalShortcut, () => settings().stepKeys);
    // The tray lists the keys that answer the current step.
    store.on('step', refreshTrayMenu);
}

function buildTray(): void {
    // Generated by scripts/make-icon.mjs and copied into dist by the build.
    const icon = nativeImage.createFromPath(join(__dirname, '..', 'tray.png'));
    tray = new Tray(icon.isEmpty() ? nativeImage.createEmpty() : icon);
    tray.on('click', () => toggleHud());
    onVoicesKnown(refreshTrayMenu);
    refreshTrayMenu();
}

/** A menu label with its key shown at the right, when there is one. */
function withKey(label: string, key: string | undefined): string {
    return key ? `${label}\t${key}` : label;
}

function refreshTrayMenu(): void {
    if (!tray) return;
    const prefs = settings();
    const step = currentStep();
    // A step lists only the keys that actually registered; between steps the
    // configured ones are shown, so the user can learn them in advance.
    const keys = step?.keys ?? { done: keyLabel(prefs.stepKeys.done), stuck: keyLabel(prefs.stepKeys.stuck) };
    const answerable = step !== null && step.mode !== 'choice';
    const noVoice = hasLocalVoice() === false;
    tray.setToolTip(
        noVoice && prefs.readStepsAloud
            ? 'Screen MCP Overlay (no local voice installed, so steps are not read aloud)'
            : 'Screen MCP Overlay'
    );
    tray.setContextMenu(
        Menu.buildFromTemplate([
            { label: mcpUrl() || 'MCP server not running', enabled: false },
            { type: 'separator' },
            { label: 'Show / hide panel\tCtrl+Shift+O', click: () => toggleHud() },
            {
                label: 'Clear and stop the current step\tCtrl+Shift+X',
                click: () => {
                    cancelStep('clear');
                    store.clear();
                }
            },
            {
                label: withKey('I did the current step', keys.done || undefined),
                enabled: answerable,
                click: () => {
                    if (step) answerStep({ kind: 'done' }, step.id);
                }
            },
            {
                label: withKey("I can't find it", keys.stuck || undefined),
                enabled: answerable,
                click: () => {
                    if (step) answerStep({ kind: 'stuck' }, step.id);
                }
            },
            {
                label: 'Copy MCP URL (includes access token)',
                click: () => {
                    clipboard.writeText(mcpAuthedUrl());
                }
            },
            { type: 'separator' },
            {
                label: 'Hide overlay from screen recording',
                type: 'checkbox',
                checked: isContentProtected(),
                click: menuItem => {
                    setContentProtection(menuItem.checked);
                    setHudContentProtection(menuItem.checked);
                    updateSettings({ showInCapture: !menuItem.checked });
                    refreshTrayMenu();
                    publishStatus();
                }
            },
            {
                label: noVoice ? 'Read steps aloud (no local voice installed)' : 'Read steps aloud',
                type: 'checkbox',
                checked: prefs.readStepsAloud,
                click: menuItem => {
                    updateSettings({ readStepsAloud: menuItem.checked });
                    if (!menuItem.checked) stopSpeaking();
                    refreshTrayMenu();
                }
            },
            {
                label: 'Sound cues',
                type: 'checkbox',
                checked: prefs.soundCues,
                click: menuItem => {
                    updateSettings({ soundCues: menuItem.checked });
                    // The overlay plays the cues and reads the preference from its state.
                    pushState();
                    refreshTrayMenu();
                }
            },
            {
                label: 'Start automatically at login',
                type: 'checkbox',
                checked: prefs.openAtLogin,
                click: menuItem => {
                    updateSettings({ openAtLogin: menuItem.checked });
                    applyOpenAtLogin(menuItem.checked);
                    refreshTrayMenu();
                }
            },
            { type: 'separator' },
            { label: 'Quit', click: () => app.quit() }
        ])
    );
}

app.on('will-quit', () => {
    globalShortcut.unregisterAll();
});

app.on('quit', () => {
    stopIdleWatch();
    stopAnchorTracking();
    stopUia();
    void mcp?.close();
    destroyOverlay();
    disposeImageWorker();
    cleanupCaptureDir();
});
