import { app, clipboard, globalShortcut, ipcMain, Menu, nativeImage, Tray } from 'electron';
import { join } from 'node:path';
import { cleanupCaptureDir, initCaptureDir } from './capture.js';
import { cancelClicks, hasPendingClick, initClicks } from './clicks.js';
import { createHud, hudWindow, pushMessage, setHudContentProtection, setStatus, toggleHud } from './hud.js';
import { disposeImageWorker } from './imageWorker.js';
import {
    startMcpServer,
    displacedPort,
    mcpActiveRequests,
    mcpAuthedUrl,
    mcpUrl,
    type McpServerHandle
} from './mcp/server.js';
import {
    destroyOverlay,
    initOverlay,
    isContentProtected,
    setContentProtection
} from './overlay.js';
import { store } from './store.js';
import { startAnchorTracking, stopAnchorTracking } from './anchors.js';
import { stopUia } from './uia.js';
import { currentProviderLabel, initAgentHost, isBusy } from './agent/host.js';
import { applyOpenAtLogin, settings, startedHidden, updateSettings } from './settings.js';

const DEFAULT_PORT = Number(process.env.SCREEN_OVERLAY_PORT || 7777);

let tray: Tray | null = null;
let mcp: McpServerHandle | null = null;

// A second instance would fight the first for global shortcuts and bind the
// same port, so hand focus back to the running one instead.
if (!app.requestSingleInstanceLock()) {
    app.quit();
} else {
    app.on('second-instance', () => hudWindow()?.show());
    void main();
}

async function main(): Promise<void> {
    // X11 composites transparent windows only with this switch. Windows and
    // macOS handle transparency natively and the switch is a no-op there.
    if (process.platform === 'linux') {
        app.commandLine.appendSwitch('enable-transparent-visuals');
    }

    await app.whenReady();

    const prefs = settings();
    setContentProtection(!prefs.showInCapture);
    applyOpenAtLogin(prefs.openAtLogin);

    initCaptureDir();
    initOverlay();
    initClicks();
    initAgentHost();
    createHud(isContentProtected());
    if (startedHidden()) hudWindow()?.hide();
    registerIpc();
    registerShortcuts();

    try {
        mcp = await startMcpServer(DEFAULT_PORT);
        const moved = displacedPort();
        pushMessage(
            'system',
            `Overlay ready on ${mcp.url}. Access requires a token — use "Copy MCP URL" in the tray ` +
                'menu, or run scripts/connect.mjs, to get the full URL.' +
                (moved
                    ? ` NOTE: port ${moved} was already in use, so this moved to ${mcp.port}. ` +
                      'Any agent configured with the old port needs updating.'
                    : '')
        );
    } catch (err) {
        pushMessage('error', `Could not start the MCP server on port ${DEFAULT_PORT}: ${(err as Error).message}`);
    }

    // Keeps anchored annotations glued to the windows and controls they point at.
    startAnchorTracking();

    buildTray();
    publishStatus();
    setInterval(publishStatus, 2000).unref?.();

    // This is a tray app; closing the panel should not exit.
    app.on('window-all-closed', () => {
        /* keep running */
    });
}

function publishStatus(): void {
    setStatus({
        mcpUrl: mcpUrl(),
        mcpConnected: mcpActiveRequests(),
        contentProtection: isContentProtected(),
        provider: currentProviderLabel(),
        busy: isBusy()
    });
}

function registerIpc(): void {
    ipcMain.handle('app:clear-annotations', () => {
        store.clear();
    });
    ipcMain.handle('app:copy-mcp-url', () => {
        // The authed form, otherwise pasting it anywhere yields 401.
        clipboard.writeText(mcpAuthedUrl());
        pushMessage('system', 'MCP URL copied to the clipboard.');
    });
    ipcMain.on('app:hide-hud', () => hudWindow()?.hide());
}

function registerShortcuts(): void {
    // Toggle the chat panel.
    globalShortcut.register('Control+Shift+O', () => toggleHud());
    // Panic button: wipe everything drawn on screen.
    globalShortcut.register('Control+Shift+X', () => store.clear());

    // Escape is grabbed ONLY while a click request is pending. A permanent
    // global registration would swallow Escape from every other application on
    // the machine for as long as the overlay runs.
    store.on('click-request', () => {
        if (hasPendingClick()) {
            globalShortcut.register('Escape', () => cancelClicks());
        } else {
            globalShortcut.unregister('Escape');
        }
    });
}

function buildTray(): void {
    // Generated by scripts/make-icon.mjs and copied into dist by the build.
    const icon = nativeImage.createFromPath(join(__dirname, '..', 'tray.png'));
    tray = new Tray(icon.isEmpty() ? nativeImage.createEmpty() : icon);
    tray.on('click', () => toggleHud());
    tray.setToolTip('Screen MCP Overlay');
    refreshTrayMenu();
}

function refreshTrayMenu(): void {
    if (!tray) return;
    tray.setContextMenu(
        Menu.buildFromTemplate([
            { label: mcpUrl() || 'MCP server not running', enabled: false },
            { type: 'separator' },
            { label: 'Show / hide panel\tCtrl+Shift+O', click: () => toggleHud() },
            { label: 'Clear annotations\tCtrl+Shift+X', click: () => store.clear() },
            {
                label: 'Copy MCP URL (includes access token)',
                click: () => {
                    clipboard.writeText(mcpAuthedUrl());
                }
            },
            { type: 'separator' },
            {
                label: 'Hide overlay from screen recording',
                type: 'checkbox',
                checked: isContentProtected(),
                click: menuItem => {
                    setContentProtection(menuItem.checked);
                    setHudContentProtection(menuItem.checked);
                    updateSettings({ showInCapture: !menuItem.checked });
                    refreshTrayMenu();
                    publishStatus();
                }
            },
            {
                label: 'Start automatically at login',
                type: 'checkbox',
                checked: settings().openAtLogin,
                click: menuItem => {
                    updateSettings({ openAtLogin: menuItem.checked });
                    applyOpenAtLogin(menuItem.checked);
                    refreshTrayMenu();
                }
            },
            { type: 'separator' },
            { label: 'Quit', click: () => app.quit() }
        ])
    );
}

app.on('will-quit', () => {
    globalShortcut.unregisterAll();
});

app.on('quit', () => {
    stopAnchorTracking();
    stopUia();
    void mcp?.close();
    destroyOverlay();
    disposeImageWorker();
    cleanupCaptureDir();
});
