import { build, context } from 'esbuild';
import { cpSync, existsSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'dist');
const watch = process.argv.includes('--watch');

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

/**
 * Main and preload run in Node/Electron and keep their dependencies external so
 * the Agent SDK's bundled CLI and native bits are loaded from node_modules
 * rather than inlined. Renderers are bundled because they have no Node access.
 */
const nodeSide = {
    platform: 'node',
    format: 'cjs',
    target: 'node22',
    bundle: true,
    sourcemap: true,
    // Only genuinely un-bundleable deps stay external. The Agent SDK ships a
    // bundled CLI binary and must be loaded from node_modules; everything else
    // (MCP SDK, zod) inlines cleanly and keeps the packaged app smaller.
    external: ['electron', '@anthropic-ai/claude-agent-sdk'],
    logLevel: 'info'
};

const browserSide = {
    platform: 'browser',
    format: 'iife',
    target: 'chrome128',
    bundle: true,
    sourcemap: true,
    logLevel: 'info'
};

const configs = [
    { ...nodeSide, entryPoints: [join(root, 'src/main/index.ts')], outfile: join(out, 'main/index.js') },
    { ...nodeSide, entryPoints: [join(root, 'src/preload/overlay.ts')], outfile: join(out, 'preload/overlay.js') },
    { ...nodeSide, entryPoints: [join(root, 'src/preload/hud.ts')], outfile: join(out, 'preload/hud.js') },
    {
        ...browserSide,
        entryPoints: [join(root, 'src/renderer/overlay/overlay.ts')],
        outfile: join(out, 'renderer/overlay/overlay.js')
    },
    {
        ...browserSide,
        entryPoints: [join(root, 'src/renderer/hud/hud.ts')],
        outfile: join(out, 'renderer/hud/hud.js')
    }
];

function copyStatic() {
    // Tray bitmap, generated by scripts/make-icon.mjs. Lives in dist/ so the
    // same relative path works in development and inside the asar archive.
    const tray = join(root, 'build/tray.png');
    if (existsSync(tray)) cpSync(tray, join(out, 'tray.png'));

    for (const name of ['overlay', 'hud']) {
        const dest = join(out, 'renderer', name);
        mkdirSync(dest, { recursive: true });
        cpSync(join(root, 'src/renderer', name, 'index.html'), join(dest, 'index.html'));
        cpSync(join(root, 'src/renderer', name, `${name}.css`), join(dest, `${name}.css`));
    }
}

if (watch) {
    const ctxs = await Promise.all(configs.map(c => context(c)));
    await Promise.all(ctxs.map(c => c.watch()));
    copyStatic();
    console.log('watching for changes…');
} else {
    await Promise.all(configs.map(c => build(c)));
    copyStatic();
    console.log('build complete');
}
